name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      uses: 'classroom-resources/autograding-io-grader@v1'
      id: run-tests
      with:
        test-name: Forge test
        setup-command: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup
        command: forge test
        comparison-method: regex
        expected-output: 2 passed
        timeout: 1
        max-score: 10
    # - name: Autograding Reporter
      # uses: classroom-resources/autograding-grading-reporter@v1
      # # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
      # # To output the results of the tests, you can use the
      # # autograding-grading-reporter action like this:
      # env:
      #   FORGE-TEST_RESULTS: "${{steps.run-tests.outputs.result}}"
      # with:
      #     runners: run-tests,